<?php

return [

    'water_company' => [
        'label' => 'المؤسسة العامة لمياه الشرب',
        'color' => 'primary',
    ],

    // --- English organizations ---
    'acted' => ['label' => 'ACTED', 'color' => 'primary'],
    'action_for_humanity' => ['label' => 'Action For Humanity', 'color' => 'primary'],
    'acu' => ['label' => 'ACU', 'color' => 'primary'],
    'adra' => ['label' => 'ADRA', 'color' => 'primary'],
    'afad' => ['label' => 'Afad', 'color' => 'primary'],
    'arhe_nova' => ['label' => 'Arhe Nova', 'color' => 'primary'],
    'bahar' => ['label' => 'Bahar', 'color' => 'primary'],
    'emergency_response_team' => ['label' => 'Emergency Response Team', 'color' => 'primary'],
    'goal' => ['label' => 'Goal', 'color' => 'primary'],
    'hand_in_hand' => ['label' => 'Hand In Hand', 'color' => 'primary'],
    'horizon_humanitarian' => ['label' => 'Horizon Humanitarian', 'color' => 'primary'],
    'human_appeal' => ['label' => 'Human Appeal', 'color' => 'primary'],
    'humanitarian_care_relief' => ['label' => 'Humanitarian Care Relief', 'color' => 'primary'],
    'ihh' => ['label' => 'IHH', 'color' => 'primary'],
    'irc' => ['label' => 'IRC', 'color' => 'primary'],
    'iyd' => ['label' => 'IYD', 'color' => 'primary'],
    'medglobal' => ['label' => 'MedGlobal', 'color' => 'primary'],
    'mentor' => ['label' => 'Mentor', 'color' => 'primary'],
    'mercy_corps' => ['label' => 'Mercy Corps', 'color' => 'primary'],
    'mercy_usa' => ['label' => 'Mercy USA', 'color' => 'primary'],
    'newday' => ['label' => 'NEWday', 'color' => 'primary'],
    'nrc' => ['label' => 'NRC', 'color' => 'primary'],
    'orange' => ['label' => 'Orange', 'color' => 'primary'],
    'people_in_need' => ['label' => 'People in Need', 'color' => 'primary'],
    'point' => ['label' => 'POINT', 'color' => 'primary'],
    'reach' => ['label' => 'Reach', 'color' => 'primary'],
    'sams' => ['label' => 'SAMS', 'color' => 'primary'],
    'sard' => ['label' => 'SARD', 'color' => 'primary'],
    'sdi' => ['label' => 'SDI', 'color' => 'primary'],
    'sema' => ['label' => 'SEMA', 'color' => 'primary'],
    'sened' => ['label' => 'Sened', 'color' => 'primary'],
    'solidarites_international' => ['label' => 'Solidarites International', 'color' => 'primary'],
    'srd' => ['label' => 'SRD', 'color' => 'primary'],
    'ssch' => ['label' => 'SSCH', 'color' => 'primary'],
    'syria_charity' => ['label' => 'Syria Charity', 'color' => 'primary'],
    'syria_relief' => ['label' => 'Syria Relief', 'color' => 'primary'],
    'uossm' => ['label' => 'UOSSM', 'color' => 'primary'],
    'world_vion' => ['label' => 'World Vision Syria Response', 'color' => 'primary'],

    // --- Arabic organizations ---
    'islamic_relief' => ['label' => 'الإغاثة الإسلامية', 'color' => 'success'],
    'international_relief' => ['label' => 'الإغاثة الدولية', 'color' => 'success'],
    'international_medical' => ['label' => 'الأطباء الدوليين aid / أتراك', 'color' => 'success'],
    'al_amal' => ['label' => 'الأمل الخيرية', 'color' => 'success'],
    'white_hands' => ['label' => 'الأيادي البيضاء', 'color' => 'success'],
    'ayade' => ['label' => 'الأيادي للإغاثة والتنمية', 'color' => 'success'],
    'al_bir_wa_ihsan' => ['label' => 'البر و الإحسان', 'color' => 'success'],
    'al_bashir' => ['label' => 'البشير', 'color' => 'success'],
    'al_bunyan_al_marsus' => ['label' => 'البنيان المرصوص', 'color' => 'success'],
    'syrian_relief_association' => ['label' => 'الجمعية السورية للإغاثة والتنمية', 'color' => 'success'],
    'white_helmets' => ['label' => 'الدفاع المدني السوري', 'color' => 'danger'],
    'rahma_volunteer' => ['label' => 'الرحمة التطوعي / مزن', 'color' => 'success'],
    'al_risala' => ['label' => 'الرسالة / جمعية إيلاف', 'color' => 'success'],
    'al_seraj' => ['label' => 'السراج', 'color' => 'success'],
    'al_salam' => ['label' => 'السلام', 'color' => 'success'],
    'alaeila' => ['label' => 'العائلة', 'color' => 'success'],
    'french_relief' => ['label' => 'الفرنسية للإغاثة', 'color' => 'success'],
    'big_heart' => ['label' => 'القلب الكبير', 'color' => 'success'],
    'global_communities' => ['label' => 'المجتمعات العالمية', 'color' => 'success'],
    'medical' => ['label' => 'الميديكال', 'color' => 'success'],
    'islamic_renaissance' => ['label' => 'النهضة الإسلامية', 'color' => 'success'],
    'al_huda_baraka' => ['label' => 'الهدى/ بركة', 'color' => 'success'],
    'sarc' => ['label' => 'الهلال الأحمر العربي السوري', 'color' => 'danger'],
    'turkish_red_crescent' => ['label' => 'الهلال التركي', 'color' => 'danger'],
    'qatari_red_crescent' => ['label' => 'الهلال القطري', 'color' => 'danger'],
    'sar' => ['label' => 'الوكالة السورية للانقاذ SAR', 'color' => 'success'],
    'amesa' => ['label' => 'اميسا', 'color' => 'success'],
    'ansor' => ['label' => 'انصر', 'color' => 'success'],
    'ihsan' => ['label' => 'إحسان', 'color' => 'success'],
    'ihsan_german' => ['label' => 'إحسان الألماني', 'color' => 'success'],
    'emar' => ['label' => 'إعمار', 'color' => 'success'],
    'iqra' => ['label' => 'إقرأ / بيرامة', 'color' => 'success'],
    'imdad' => ['label' => 'إمداد', 'color' => 'success'],
    'elaf' => ['label' => 'إيلاف', 'color' => 'success'],
    'doctors_world' => ['label' => 'أطباء العالم', 'color' => 'success'],
    'msf_spain' => ['label' => 'أطباء بلا حدود / اسبانيا', 'color' => 'success'],
    'msf_belgium' => ['label' => 'أطباء بلا حدود / بلجيكيا', 'color' => 'success'],
    'msf_france' => ['label' => 'أطباء بلا حدود / فرنسا', 'color' => 'success'],
    'doctors_across_continents' => ['label' => 'أطباء عبر القارات', 'color' => 'success'],
    'doctors_syria' => ['label' => 'أطباء في سوريا', 'color' => 'success'],
    'umma' => ['label' => 'أمة الخيرية', 'color' => 'success'],
    'amal_development' => ['label' => 'أمل للإغاثة والتنمية', 'color' => 'success'],
    'ahl_al_hadith' => ['label' => 'أهل الحديث', 'color' => 'success'],
    'afaq' => ['label' => 'آفاق للتطوير والتغير', 'color' => 'success'],
    'basma' => ['label' => 'بسمة', 'color' => 'success'],
    'basmat_amal' => ['label' => 'بسمة أمل', 'color' => 'success'],
    'balad' => ['label' => 'بلد', 'color' => 'success'],
    'bina' => ['label' => 'بناء للتنمية', 'color' => 'success'],
    'banafsaj' => ['label' => 'بنفسج', 'color' => 'success'],
    'bunyan' => ['label' => 'بنيان', 'color' => 'success'],
    'birama' => ['label' => 'بيرامة', 'color' => 'success'],
    'takafal_alsham' => ['label' => 'تكافل الشام', 'color' => 'success'],
    'takafal_austria' => ['label' => 'تكافل النمسا', 'color' => 'success'],
    'haq_association' => ['label' => 'جمعية حق', 'color' => 'success'],
    'childhood_protectors' => ['label' => 'حراس الطفولة', 'color' => 'success'],
    'hifz_alnima' => ['label' => 'حفظ النعمة', 'color' => 'success'],
    'syrian_env_protection' => ['label' => 'حماية البيئة السورية', 'color' => 'success'],
    'kheir_umma' => ['label' => 'خير أمة', 'color' => 'success'],
    'darna' => ['label' => 'دارنا', 'color' => 'success'],
    'houran_association' => ['label' => 'رابطة أهل حوران', 'color' => 'success'],
    'rahma_humanity' => ['label' => 'رحمة الإنسانية', 'color' => 'success'],
    'rahma_world' => ['label' => 'رحمة العالمية', 'color' => 'success'],
    'rahma_limitless' => ['label' => 'رحمة بلا حدود', 'color' => 'success'],
    'rahma_around_world' => ['label' => 'رحمة حول العالم', 'color' => 'success'],
    'rasha_shaam' => ['label' => 'رسالة الشام الإنسانية', 'color' => 'success'],
    'saed' => ['label' => 'ساعد', 'color' => 'success'],
    'sakhaw_ataa' => ['label' => 'سخاء وعطاء', 'color' => 'success'],
    'sadad' => ['label' => 'سداد', 'color' => 'success'],
    'sanad' => ['label' => 'سند الخيرية', 'color' => 'success'],
    'syria_aid' => ['label' => 'سوريا للمساعدات الإنسانية و التنمية', 'color' => 'success'],
    'sham_insaniya' => ['label' => 'شام الإنسانية', 'color' => 'success'],
    'sham_kheir' => ['label' => 'شام الخير', 'color' => 'success'],
    'sham_sharif' => ['label' => 'شام شريف', 'color' => 'success'],
    'sham_orphans' => ['label' => 'شام للأيتام', 'color' => 'success'],
    'shafaq' => ['label' => 'شفق', 'color' => 'success'],
    'silk_road' => ['label' => 'طريق الحرير', 'color' => 'success'],
    'ataa_atma' => ['label' => 'عطاء للإغاثة الإنسانية / أطمة', 'color' => 'success'],
    'ataa_sarmada' => ['label' => 'عطاء للإغاثة الإنسانية / سرمدا', 'color' => 'success'],
    'grass_kheir' => ['label' => 'غراس الخير', 'color' => 'success'],
    'grass_nahda' => ['label' => 'غراس النهضة', 'color' => 'success'],
    'ghasaq' => ['label' => 'غسق', 'color' => 'success'],
    'ghosn_zaytoon' => ['label' => 'غصن الزيتون', 'color' => 'success'],
    'faeil_kheir' => ['label' => 'فاعل خير', 'color' => 'success'],
    'fath_dar' => ['label' => 'فتح دار', 'color' => 'success'],
    'qatar_charity' => ['label' => 'قطر الخيرية', 'color' => 'info'],
    'kahatayn' => ['label' => 'كهاتين', 'color' => 'success'],
    'madad' => ['label' => 'مداد الإنسانية', 'color' => 'success'],
    'maram' => ['label' => 'مرام', 'color' => 'success'],
    'marj_dabiq' => ['label' => 'مرج دابق', 'color' => 'success'],
    'muzn' => ['label' => 'مزن', 'color' => 'success'],
    'peace_space' => ['label' => 'مساحة السلام', 'color' => 'success'],
    'masar' => ['label' => 'مسار', 'color' => 'success'],
    'masrat' => ['label' => 'مسرات', 'color' => 'success'],
    'masek' => ['label' => 'مسك', 'color' => 'success'],
    'mudmar' => ['label' => 'مضمار / صنوبر', 'color' => 'success'],
    'matar' => ['label' => 'مطر', 'color' => 'success'],
    'childcare' => ['label' => 'مكتب رعاية الطفولة و الامومة', 'color' => 'success'],
    'molham' => ['label' => 'ملهم التطوعي', 'color' => 'success'],
    'minbar_alshaam' => ['label' => 'منبر الشام', 'color' => 'success'],
    'women_foundation' => ['label' => 'مؤسسة المرأة السورية للإغاثة والتنمية', 'color' => 'success'],
    'skt' => ['label' => 'مؤسسة سكن للرعاية والتنمية SKT', 'color' => 'success'],
    'nasaem_alkheir' => ['label' => 'نسائم الخير', 'color' => 'success'],
    'hayati' => ['label' => 'هذه حياتي', 'color' => 'success'],
    'ihr' => ['label' => 'هيئة الإغاثة الإنسانية IHR', 'color' => 'success'],
    'hrc' => ['label' => 'هيئة العمل الإنساني HRC', 'color' => 'success'],
    'palestine' => ['label' => 'هيئة فلسطين الخيرية', 'color' => 'success'],
    'watan' => ['label' => 'وطن', 'color' => 'success'],
    'turkey_waqf' => ['label' => 'وقف الديانة التركي', 'color' => 'danger'],
    'environment_agency' => ['label' => 'وكالة حماية البيئة', 'color' => 'success'],
];
